### PR TITLE
add leaflet map input

### PR DESCRIPTION
**Pull request by PeterTheOne**
This PR adds a leaflet map input besides the already existing googlemaps and openlayers ones.

@yaronkoren Can you merge this PR, should I send you a patch file or how does this work? I'm not used to Gerrit.

/cc @krabina

### CODE REVIEW

**Comment by yaronkoren** [comment]
Wow! I didn't know adding Leaflet support could be so (relatively) simple.
Should this take in any extra parameters, like the mapping service to be used, etc.?
I don't know if this patch can be merged in from here - I've only ever merged in from Gerrit, I think. (And the command line.)

**Comment by PeterTheOne** [comment]
:) It was pretty straightforward with googlemaps and openlayers implementations to look at. ;)

It can be used with `type=leaflet`, just like `type=googlemaps` and `type=openlayers`.

You should be able to pull this commit from `git@github.com:PeterTheOne/mediawiki-extensions-PageForms.git` (https://github.com/PeterTheOne/mediawiki-extensions-PageForms), merge and push it via command line.

**Comment by yaronkoren** [comment]
I'm talking about choosing the mapping service, not the input type. Doesn't Leaflet let you choose which mapping service to use, much like OpenLayers does? I really don't know much about it. What's the default mapping service it uses - Open Street Map?

**Comment by PeterTheOne** [comment]
Ah I misunderstood, Leaflet lets you choose the mapping service. I've used Open Street Map here, see https://github.com/wikimedia/mediawiki-extensions-PageForms/pull/2/files#diff-acc342a950be7c79a28281360f9dc64aR40 .

**Comment by yaronkoren** [comment]
Alright. What other mapping services can be used besides OSM? Is it worth adding support for any of them, or are they all pretty minor options compared to OSM? (Or is it worth adding support, but not right now?)

**Comment by PeterTheOne** [comment]
You can look at https://leaflet-extras.github.io/leaflet-providers/preview/ , for https://github.com/JeroenDeDauw/Maps I made them available.

**Comment by PeterTheOne** [comment]
I would say, merge it for now. And look at other layers later.. and maybe also think about implementing more geocoders or using geocoders from Maps.

**Comment by yaronkoren** [comment]
Oh wow, there are some very nice maps there.

**Comment by PeterTheOne** [comment]
@yaronkoren Can you merge this? ^^

**Comment by yaronkoren** [comment]
@PeterTheOne - sorry for the long delay on this. This addition has been on my to-do list for a long time now. There have actually been a number of changes to the PF maps code over the last few months, and I wanted to take care of those before I got to this (for no strong reason). As luck would have it, I just merged in the last of those big changes earlier today, so I should be able to get to this soon.

**Comment by PeterTheOne** [comment]
@yaronkoren Thanks :+1: There seems to be some conflicts now, I hope it doesn't complicate things.

**Comment by yaronkoren** [comment]
I meant to ask this before - can the Leaflet JS and CSS files be moved into the Page Forms repository? Is there any benefit to using the remote files? Does it matter?

**Comment by PeterTheOne** [comment]
They can be moved and I would recommend it, also for openlayers.

**Comment by yaronkoren** [comment]
@PeterTheOne - sorry again for the delay. I'm pretty much ready to check this patch in, with some small modifications based on recent changes to the map input code. I just have one question: why do you have the default center of the map at 50, 50? It seems to display better with a default center of 0, 0.

**Comment by PeterTheOne** [comment]
@yaronkoren Oh, I just tested with `50, 50`. `0, 0` should be better..

**Comment by yaronkoren** [comment]
I merged in this patch, with a few modifications, so Page Forms now supports Leaflet. Thank you!

**Pull request closed without merging**
